### ISSUE TITLE
(warning) 'com.haberey/nsd' channel message on a non-platform thread

### ISSUE THREAD

**Issue by robert-virkus** [sebastianhaberey/nsd#51] opened 2023-11-03 11:45 UTC
### Description

Hi, here's just a warning from the Flutter environment. Does not seem to impact functionality yet, but this probably should be addressed.

GIVEN I run a Flutter Windows app on Windows 11 with Flutter 3.13.8
WHEN trying to register a service with `register` / `Future<Registration> register(Service service)`
THEN I receive the  following warning: `[ERROR:flutter/shell/common/shell.cc(1004)] The 'com.haberey/nsd' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel. `

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

Windows

**Comment by sebastianhaberey** [comment] 2023-11-03 11:52
Hi Robert, you are right this is indeed the cause of a currently open issue: #46 So I'm closing this as a duplicate.

**Closed by sebastianhaberey** 2023-11-03 11:52 UTC
Labels: duplicate
