### ISSUE TITLE
Several strange behaviors, maybe Android

### ISSUE THREAD

**Issue by Erhannis** [sebastianhaberey/nsd#34] opened 2022-11-23 00:48 UTC
### Description

I'm writing [a library](https://github.com/Erhannis/flutter_zeroconnect) gluing automagic communications over NSD, and experiencing some strange behavior.  I'm currently [testing](https://github.com/Erhannis/flutter_zeroconnect_test), on:
* (thing, service type, name)
* A windows laptop, _WORK._tcp, 1d31fa57-150d-4f50-b4e7-6393695e3d40
* A windows desktop, _DESK._tcp, bbae63ae-9a38-4cfb-81e2-50c34e9f444b
* An Android phone, _NOTE._tcp, 7cf86e76-fa59-4647-ad2a-957af064c3c0
* An Android phone, _PIXEL._tcp, 2dbf73d1-74c4-4c1c-86fc-6bf7d2696288

They all have wifi, but DESK also has several other interfaces.

Note that apparently on Android, registering a Service gives registration.service.host == null, so...well, I suddenly realize some of my code is pointless, but I don't think that particular thing is the problem.  (Side note: is there an easy way to get the host before registering, so I can add the ip addresses to `addresses` _before_ registering a host potentially with no way to contact it?)

But anyway.  Test results.  (Note that I filtered out self-scans, and only tried to connect to things that showed up in a scan.)

Scanning:
Everything shows up in everything else's scans, _except_ that PIXEL shows up for NOTE but not for DESK or WORK.

Trying to connect to scanned things:
Nothing can connect to WORK (but I think that's a firewall thing, so that's ok).
Everything can connect to DESK.
Initially WORK failed to connect to NOTE, and I don't know why, but on a second attempt it succeeded.
So, WORK and PIXEL but not DESK can connect to NOTE.
NOTE can connect to PIXEL (but was the only thing that could scan it, anyway).

Here's some more info, from console commands on DESK.
```
C:\Users\Erhannis>dns-sd -B _WORK._tcp
Browsing for _WORK._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
19:00:38.130  Add     2 15 local.                    _WORK._tcp.               1d31fa57-150d-4f50-b4e7-6393695e3d40
^C
C:\Users\Erhannis>dns-sd -B _DESK._tcp
Browsing for _DESK._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
19:00:47.243  Add     3  4 local.                    _DESK._tcp.               bbae63ae-9a38-4cfb-81e2-50c34e9f444b
19:00:47.244  Add     3  5 local.                    _DESK._tcp.               bbae63ae-9a38-4cfb-81e2-50c34e9f444b
19:00:47.244  Add     2 15 local.                    _DESK._tcp.               bbae63ae-9a38-4cfb-81e2-50c34e9f444b
^C
C:\Users\Erhannis>dns-sd -B _NOTE._tcp
Browsing for _NOTE._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
19:01:07.796  Add     2 15 local.                    _NOTE._tcp.               7cf86e76-fa59-4647-ad2a-957af064c3c0
^C
C:\Users\Erhannis>dns-sd -B _PIXEL._tcp
Browsing for _PIXEL._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
19:01:21.062  Add     2 15 local.                    _PIXEL._tcp.              2dbf73d1-74c4-4c1c-86fc-6bf7d2696288
^C
C:\Users\Erhannis>dns-sd -L 1d31fa57-150d-4f50-b4e7-6393695e3d40 _WORK._tcp
Lookup 1d31fa57-150d-4f50-b4e7-6393695e3d40._WORK._tcp.local
19:01:48.586  1d31fa57-150d-4f50-b4e7-6393695e3d40._WORK._tcp.local. can be reached at mewer-intune.local.:63418 (interface 15)
^C
C:\Users\Erhannis>dns-sd -L bbae63ae-9a38-4cfb-81e2-50c34e9f444b _DESK._tcp
Lookup bbae63ae-9a38-4cfb-81e2-50c34e9f444b._DESK._tcp.local
19:02:12.467  bbae63ae-9a38-4cfb-81e2-50c34e9f444b._DESK._tcp.local. can be reached at DESKTOP-F6GR5LG.local.:23209 (interface 4) Flags: 1
19:02:12.467  bbae63ae-9a38-4cfb-81e2-50c34e9f444b._DESK._tcp.local. can be reached at DESKTOP-F6GR5LG.local.:23209 (interface 5) Flags: 1
19:02:12.468  bbae63ae-9a38-4cfb-81e2-50c34e9f444b._DESK._tcp.local. can be reached at DESKTOP-F6GR5LG.local.:23209 (interface 15)
^C
C:\Users\Erhannis>dns-sd -L 7cf86e76-fa59-4647-ad2a-957af064c3c0 _NOTE._tcp
Lookup 7cf86e76-fa59-4647-ad2a-957af064c3c0._NOTE._tcp.local
19:02:33.093  7cf86e76-fa59-4647-ad2a-957af064c3c0._NOTE._tcp.local. can be reached at Android.local.:37047 (interface 15)
^C
C:\Users\Erhannis>dns-sd -L 2dbf73d1-74c4-4c1c-86fc-6bf7d2696288 _PIXEL._tcp
Lookup 2dbf73d1-74c4-4c1c-86fc-6bf7d2696288._PIXEL._tcp.local
19:03:03.779  2dbf73d1-74c4-4c1c-86fc-6bf7d2696288._PIXEL._tcp.local. can be reached at Android-3.local.:41299 (interface 15)
^C
C:\Users\Erhannis>ping mewer-intune.local

Pinging mewer-intune [fe80::3177:7fce:7436:b7f5%15] with 32 bytes of data:
Reply from fe80::3177:7fce:7436:b7f5%15: time=2ms
Reply from fe80::3177:7fce:7436:b7f5%15: time=4ms
Reply from fe80::3177:7fce:7436:b7f5%15: time=9ms
Reply from fe80::3177:7fce:7436:b7f5%15: time=4ms

Ping statistics for fe80::3177:7fce:7436:b7f5%15:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 9ms, Average = 4ms

C:\Users\Erhannis>ping DESKTOP-F6GR5LG.local

Pinging DESKTOP-F6GR5LG [fe80::2012:a99a:2011:43ff%4] with 32 bytes of data:
Reply from fe80::2012:a99a:2011:43ff%4: time<1ms
Reply from fe80::2012:a99a:2011:43ff%4: time<1ms
Reply from fe80::2012:a99a:2011:43ff%4: time<1ms
Reply from fe80::2012:a99a:2011:43ff%4: time<1ms

Ping statistics for fe80::2012:a99a:2011:43ff%4:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

C:\Users\Erhannis>ping Android.local

Pinging Android.local [192.168.1.43] with 32 bytes of data:
Reply from 192.168.1.43: bytes=32 time=81ms TTL=64
Reply from 192.168.1.43: bytes=32 time=93ms TTL=64
Reply from 192.168.1.43: bytes=32 time=108ms TTL=64
Reply from 192.168.1.43: bytes=32 time=16ms TTL=64

Ping statistics for 192.168.1.43:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 16ms, Maximum = 108ms, Average = 74ms

C:\Users\Erhannis>ping Android-3.local
Ping request could not find host Android-3.local. Please check the name and try again.

C:\Users\Erhannis>
```

Note that `dns-sd` was able to see PIXEL's service, but the reported host was unresolvable.  Contrasted with NSD, which did not show it in the scan.

I also note that PIXEL, to the Android phones, is `Pixel-4a.lan`, and NOTE is `android-[buncha characters].lan`, and from DESK, pinging `Pixel-4a.lan` succeeds.

Any idea why PIXEL is only showing up in scans for the other Android?  The difference in naming, perhaps?  Does NSD resolve the host before confirming the scan?  Any idea how to get it to work consistently?  (And any idea why the connection might have initially failed from DESK to NOTE?)

### Scenario

Use the plugin in my own application via Flutter dependency

### Platform

All of them

**Comment by sebastianhaberey** [comment] 2022-11-26 12:10
> Note that apparently on Android, registering a Service gives registration.service.host == null

Yes, Android's NsdManager doesn't set the host on the registered service. It's the same on macOS and iOS. Only Windows API will set the host there AFAIK.

> Side note: is there an easy way to get the host before registering, so I can add the ip addresses to addresses before registering a host potentially with no way to contact it?

The host will only be `null` when _registering_ services. It basically means "localhost". When _discovering_ services, there should always be a valid host name in the service object, even for services that are on the same host.

> Any idea why PIXEL is only showing up in scans for the other Android?

So if I understand it correctly, your Android Pixel device doesn't appear in the nsd example app on your two Windows machines. But when you run `dns-sd` on the same machines, it shows up. Right?

First, the Pixel's host name "Android-3.local" doesn't seem to be resolvable in your network. This seems strange, maybe you could investigate that. This could definitely be a problem for the plugin [if you have IP lookup enabled](https://pub.dev/packages/nsd#advanced-usage). But I had a short look at your code and I don't think you do.

Second, I agree with you that if `dns-sd` lists the service, the plugin should too. Could you try the following:

Open the example app on your Windows machine with Android Studio. Modify the follwing part in nsd/nsd/example/lib/main.dart:

```
  MyAppState() {
    enableLogging(LogTopic.calls);
    enableLogging(LogTopic.errors); // add this line
  }
```

Now start the example app using Android Studio. You should see log messages such as

```
[MethodChannelNsdPlatform] [2022-11-26 12:30:30.065382] [calls] Callback: onServiceDiscovered {handle: f66df09b-d98f-4dae-82de-ebc5a412b674, service.name: Some Service(1), service.type: _http._tcp}
```

Now start the PIXEL service on your Android device and see if anything related to the Pixel device comes up. Or anything dodgy such as errors.

BTW is any of your devices Android 13?

**Comment by sebastianhaberey** [comment] 2022-11-26 12:23
P.S.: also, it seems like there's two competing domains in your network: _local_ and _lan_. If I had to guess, that could have something to do with it. I.e. not all devices are in all the domains.

**Comment by sebastianhaberey** [comment] 2022-12-18 14:26
Since I cannot reproduce this issue in my environment, I'll close it for now. Feel free to file another issue if the problem should persist.

**Closed by sebastianhaberey** 2022-12-18 14:26 UTC
Labels: waiting for user feedback
