### ISSUE TITLE
Maximum outstanding requests reached

### ISSUE THREAD

**Issue by darshitpolaris** [sebastianhaberey/nsd#13] opened 2022-02-23 11:09 UTC
I got this error "Unhandled Exception: NsdError (message: "Maximum outstanding requests reached", cause: maxLimit)" 

- After getting some discovery I got this 
- After uninstalling the app I got a new discovery but still, this exception arrive.

How I can solve this error?

**Comment by sebastianhaberey** [comment] 2022-02-24 04:00
Hi @darshitpolaris,

the errors thrown by the plugin are documented [here](https://pub.dev/documentation/nsd_platform_interface/latest/nsd_platform_interface/ErrorCause.html):

> maxLimit → const [ErrorCause](https://pub.dev/documentation/nsd_platform_interface/latest/nsd_platform_interface/ErrorCause.html)
>
> Indicates too many "outstanding requests" - on Android (30) this seems to be 10 operations (running discoveries and active registrations combined).

My guess is that you have more than 10 simultaneous discoveries and / or registrations active. Make sure that you stop discoveries you don't need anymore:

```Dart
await stopDiscovery(discovery);
```

Likewise, unregister all services you don't need anymore:

```Dart
await unregister(registration);
```

**Comment by darshitpolaris** [comment] 2022-02-24 13:34
```
await startDiscovery('_http._tcp', ipLookupType: IpLookupType.any).then(
      (discovery) async => discovery.addListener(
        () {
          discoveryServicesListClear();
          for (var element in discovery.services) {
          }
        },
```

>  I'm not getting you properly,

This is my code to get network service discovery.
Guide me on how to improve this code.

**Comment by sebastianhaberey** [comment] 2022-02-25 02:42
This part of your code seems fine to me. But is it called more than once? 

For example, if you were to put this code in the `build()` method of a stateless widget, this would start a new discovery every time the widget redraws and lead to the max limit error.

**Comment by darshitpolaris** [comment] 2022-02-25 04:35
> This part of your code seems fine to me. But is it called more than once?
> 
> For example, if you were to put this code in the `build()` method of a stateless widget, this would start a new discovery every time the widget redraws and lead to the max limit error.

**Comment by darshitpolaris** [comment] 2022-02-25 04:38
Ye this part is called in main  Whenever I refresh the UI this part is always call,
Suggest me how to improve this if I get new discoveries every time in my code.

**Comment by sebastianhaberey** [comment] 2022-02-25 05:21
Have a look at the [example application](https://github.com/sebastianhaberey/nsd/blob/main/nsd/example/lib/main.dart). It creates a `StatfulWidget` and a corresponding `State`. The started discoveries are properties of the state, so they are preserved during UI refreshes. 

Don't forget to stop the discovery properly (for example in the State's `dispose()` method).

**Comment by sebastianhaberey** [comment] 2022-02-28 10:43
I'm closing this since it's most likely not a bug in the plugin. Please do open another issue if there's a bug that needs fixing.

**Closed by sebastianhaberey** 2022-02-28 10:43 UTC
